### PR TITLE
Add gnuplot support

### PR DESCRIPTION
**Pull request by coolreader18**
Depends on #3

image

The key things that enable this in libqalculate are `qalc_gnuplot_data_dir`/`qalc_invoke_gnuplot` in entry.cpp and passing `--with-gnuplot=byo` to configure, which were added in qalculate/libqalculate#281.

cc @hanna-kn, this is what I was working on with bring-your-own gnuplot.

### CODE REVIEW

**Comment by flaviut** [comment]
This is very cool! nice work! The only concern I'd have here is about bundle size, 5-ish MB is already pretty big, and honestly it just takes a lot of time to load. I don't know if it's possible to do code splitting or something to only load gnuplot on demand, but it'd probably be nice.

**Comment by coolreader18** [comment]
That already happens, actually! gnuplot is loaded in a worker which isn't initialized until `plot()` is called.

**Comment by coolreader18** [comment]
Before plot:

image

After plot:

image

**Comment by coolreader18** [comment]
That build failure is so weird - I fixed something like that ICONV_CONST error in 558fe94, and it works fine on my machine.

**Comment by coolreader18** [comment]
Ah, ok, [here's the log error](https://github.com/coolreader18/qalculate-wasm/runs/2651310856?check_suite_focus=true#step:6:842)

**Pull request merged**
